### ISSUE TITLE
Upgrade to Spring Boot 3.4.x

### ISSUE THREAD

**Issue by xhaggi** [wimdeblauwe/htmx-spring-boot#147]
Spring Boot [3.4.0](https://github.com/spring-projects/spring-boot/milestone/353) is scheduled for release on November 21, 2024.

**Todos**

- [x] Bump version to 4.0.0-SNAPSHOT
- [x] Update Spring dependencies
- [x] Check if `HtmxView` could be replaced by [HTML Fragments](https://docs.spring.io/spring-framework/reference/web/webmvc-view/mvc-fragments.html) support of Spring Framework 6.2
- [x] Remove deprecated code parts
- [x] Refactor tests: Move controllers into related test classes

@wimdeblauwe let me know if anything is missing.

**Comment by wimdeblauwe** [comment]
On my other project https://github.com/wimdeblauwe/error-handling-spring-boot-starter/, I have set up separate documentation per version. I wonder if we should introduce the same (or similar) mechanism here so that people on older versions can still find the documentation for their version?
